name: Docker Build and Push

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Build and push the image
        run : |
          docker login --username mikeed12 --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/mikeed12/reqcore:latest
          docker push ghcr.io/mikeed12/reqcore:latest
